
spring:
  application:
    name: api-manager
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

  freemarker:
    request-context-attribute: request
    settings:
      number_format: 0.##########
    template-loader-path: classpath:/templates/
    suffix: .ftl
    charset: UTF-8

  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://imjcker.synology.me:3306/api-manager?Unicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 30
      max-idle: 30
      test-on-borrow: true
      validation-query: SELECT 1
      validation-interval: 30000


server:
  port: 8089

mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml


logging:
  file: ${user.home}/logs/${spring.application.name}.log
  level: info