server:
  port: 9999

imjcker: hello from scheduler

spring:
  application:
    name: spring-cloud-service-scheduler
  datasource:
    url: jdbc:mysql://localhost:3306/quartz
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 200
      max-wait: 10000
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      aop-patterns: com.imjcker.spring.cloud.service.*


