spring:
  application:
    name: imjcker
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
#    url: jdbc:mysql://localhost:3306/management?useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:h2:~/imjcker
    driver-class-name: org.h2.Driver
    username: root
    password: mysql
  mail:
    host: smtp.qq.com
    username: 1335111211@qq.com
    password: ovitqwivhagghcaf
    properties:
      mail:
        smptp:
          auth: true
          starttls:
            enable: true
            required: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
site:
  domain: imjcker.com

logging:
  level:
    root: info
    com.imjcker: info
  file: ${user.home}/logs/${spring.application.name}.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} -%5p [%t] %-40.40logger{39} : %X{uuid} %m%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} -%5p [%t] %-40.40logger{39} : %X{uuid} %m%n"


# github oauth for prod domain: www.imjcker.com
#oauth:
#  github:
#    user: imjcker
#    client-id: c004b44b60446382aac4
#    client-secret: bd8b8dfa7203b036d4e444c9854e83878ead409e
#    redirect_uri: http://www.imjcker.com/oauth/github/callback

# 开启logger 追加UUID
logAop:
  uuid: true

robot:
  turing:
    user-id: ${USER_ID:helloalanturing}
    api-key: ${API_KEY:7891e8bbdf5b4315a35acf9a0bedfafa}
server:
  port: 80